### ISSUE TITLE
CSV output column order varies on each call

### ISSUE THREAD

**Issue by tborgstadt** [NikolaiT/GoogleScraper#132]
I'm going to use a query to the database instead but did notice this nuance.

CSV output columns are in different order everytime I initiate GoogleScraper. I didn't notice this until recently when making calls to GoogleScraper from within another application and then processing the CSV file with that application.

I notice some CSV changes were committed on 12/4. I did uninstall and reinstall GoogleScraper from GitHub and this seems to have fixed the file close issue, but the column order is still an issue.  

See screenshot of the CSV output from the 3 calls to the attached script (same config other than changing the output file name to see the differences).

Very nice tool.

![3_csv_outputs_for_same_search_ each_with_diff_col_order](https://cloud.githubusercontent.com/assets/15312425/11610277/413ca042-9b63-11e5-814d-3986810f8f65.png)
![test_script](https://cloud.githubusercontent.com/assets/15312425/11610278/413ce2e6-9b63-11e5-9ffc-0c2a5358abb4.png)

**Comment by NikolaiT** [comment]
Hi, thanks for using my tool!

Fixed by sorting the dictnames of the `CsvWriter`. I added a test in the last commit: The file <tests/integration_tests.py> now has a test `test_csv_file_header_always_the_same`
