### ISSUE TITLE
json from python module?

### ISSUE THREAD

**Issue by xjuric29** [NikolaiT/GoogleScraper#190]
Hi, is there any way to get json exactly after calling scrape_with_config? And is possible with config settings turn off creating of DB file? Thanks for respons

**Comment by xjuric29** [comment]
And if a choose scraping by Google Chrome, I can't be root, because it wants arg --no-sandbox and if I choose Firefox it's even worse, GoogleScraper selenium webdriver badly terminate and Firefox process are still running.
![snimek z 2017-08-31 12 35 37](https://user-images.githubusercontent.com/26231120/29919277-f893e848-8e48-11e7-95f3-ce21c0ac85f8.png)

**Comment by fassn** [comment]
Hello, 

This project is not updated anymore by its author. I forked and improved it some months ago, if you want to give it a test. 
But I'd rather recommend, as I abandoned my fork aswell, to check the SerpScrap project, these guys have given a new life to the project and seem to do good.

**Comment by VeeeneX** [comment]
@xjuric29 Or you can use nodejs scrapper :), but checkout @fassn's scrapper

**Comment by xjuric29** [comment]
Thank you guys :)
