### ISSUE TITLE
No results for Yandex

### ISSUE THREAD

**Issue by krawez** [NikolaiT/GoogleScraper#217]
Yandex results deliver unfortunatelly no results, though it says success

**Comment by NikolaiT** [comment]
I fixed it in the following commit: https://github.com/NikolaiT/GoogleScraper/commit/40ab7f1e0fcdaabc01f1d79be1991162755803c4

You can specify the CSS selectors for your search engine page in the file `parsing.py`. For yandex the selectors are now:

```
    normal_search_selectors = {
        'results': {
            'de_ip': {
                'container': '.serp-list',
                'result_container': '.serp-item',
                'link': 'a.link::attr(href)',
                'snippet': 'div.text-container::text',
                'title': 'div.organic__url-text::text',
                'visible_link': '.typo_type_greenurl::text'
            }
        }
    }
```
