### ISSUE TITLE
num_results_per_page is ignored?

### ISSUE THREAD

**Issue by adriadrop** [NikolaiT/GoogleScraper#222]
In scrape_config.oy I am setting this to 1
//How many results per SERP page 
num_results_per_page = 1

and then I run the command

`GoogleScraper -m http --keyword-file search_data/crypto.txt --num-workers 5  --output-filename results.csv`

but I keep getting 10 results per keyword, not 1, is this a bug or somehow I didnt make config right?
Using latest version installed with pip git

**Comment by adriadrop** [comment]
Ohh I used it wrong config is ignored when using CLI?!
Works like this

` GoogleScraper -m http --keyword-file search_data/crypto.txt --num-workers 5  --output-filename results.csv -n1`

**Comment by NikolaiT** [comment]
Google shows either 10,20,30,40,50 or 100 results per page. Other search engines a range between 10 and 100. A value of 1 is not possible. Added a check and this issue is fixed.
