### ISSUE TITLE
Issue during installation via pip install git+git://github.com/NikolaiT/GoogleScraper/

### ISSUE THREAD

**Issue by kenju254** [NikolaiT/GoogleScraper#41]
Downloading/unpacking git+git://github.com/NikolaiT/GoogleScraper/
  Cloning git://github.com/NikolaiT/GoogleScraper/ to /tmp/pip-ebq84mt9-build
  Running setup.py (path:/tmp/pip-ebq84mt9-build/setup.py) egg_info for package from git+git://github.com/NikolaiT/GoogleScraper/

Downloading/unpacking lxml (from GoogleScraper==0.1.9)
  Downloading lxml-3.4.1.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py (path:/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/lxml/setup.py) egg_info for package lxml
    Building lxml version 3.4.1.
    Building without Cython.
    ERROR: b'/bin/sh: 1: xslt-config: not found\n'
    *\* make sure the development packages of libxml2 and libxslt are installed **

```
Using build configuration of libxslt
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)

warning: no previously-included files found matching '*.py'
```

Downloading/unpacking selenium (from GoogleScraper==0.1.9)
  Downloading selenium-2.44.0.tar.gz (2.6MB): 2.6MB downloaded
  Running setup.py (path:/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/selenium/setup.py) egg_info for package selenium

Downloading/unpacking cssselect (from GoogleScraper==0.1.9)
  Downloading cssselect-0.9.1.tar.gz
  Running setup.py (path:/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/cssselect/setup.py) egg_info for package cssselect

```
no previously-included directories found matching 'docs/_build'
```

Downloading/unpacking requests (from GoogleScraper==0.1.9)
  Downloading requests-2.5.0-py2.py3-none-any.whl (464kB): 464kB downloaded
Downloading/unpacking PyMySql (from GoogleScraper==0.1.9)
  Downloading PyMySQL-0.6.3-py2.py3-none-any.whl (63kB): 63kB downloaded
Downloading/unpacking sqlalchemy (from GoogleScraper==0.1.9)
  Downloading SQLAlchemy-0.9.8.tar.gz (4.1MB): 4.1MB downloaded
  Running setup.py (path:/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/sqlalchemy/setup.py) egg_info for package sqlalchemy

```
warning: no files found matching '*.jpg' under directory 'doc'
warning: no files found matching 'distribute_setup.py'
warning: no files found matching 'sa2to3.py'
warning: no files found matching 'ez_setup.py'
no previously-included directories found matching 'doc/build/output'
```

Installing collected packages: lxml, selenium, cssselect, requests, PyMySql, sqlalchemy, GoogleScraper
  Running setup.py install for lxml
    Building lxml version 3.4.1.
    Building without Cython.
    ERROR: b'/bin/sh: 1: xslt-config: not found\n'
    *\* make sure the development packages of libxml2 and libxslt are installed **

```
Using build configuration of libxslt
building 'lxml.etree' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/lxml/src/lxml/includes -I/usr/include/python3.4m -I/home/kenju254/workspaces/reverseA/GoogleScraperP/env/include/python3.4m -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-3.4/src/lxml/lxml.etree.o -w
In file included from src/lxml/lxml.etree.c:239:0:
/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
 #include "libxml/xmlversion.h"
                               ^
compilation terminated.
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Complete output from command /home/kenju254/workspaces/reverseA/GoogleScraperP/env/bin/python3 -c "import setuptools, tokenize;__file__='/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-aimi250p-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kenju254/workspaces/reverseA/GoogleScraperP/env/include/site/python3.4:
Building lxml version 3.4.1.
```

Building without Cython.

ERROR: b'/bin/sh: 1: xslt-config: not found\n'

*\* make sure the development packages of libxml2 and libxslt are installed **

Using build configuration of libxslt

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-3.4

creating build/lib.linux-x86_64-3.4/lxml

copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/sax.py -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/**init**.py -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/builder.py -> build/lib.linux-x86_64-3.4/lxml

creating build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/**init**.py -> build/lib.linux-x86_64-3.4/lxml/includes

creating build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/**init**.py -> build/lib.linux-x86_64-3.4/lxml/html

copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.4/lxml/html

creating build/lib.linux-x86_64-3.4/lxml/isoschematron

copying src/lxml/isoschematron/**init**.py -> build/lib.linux-x86_64-3.4/lxml/isoschematron

copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.4/lxml

copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.4/lxml/includes

copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.4/lxml/includes

creating build/lib.linux-x86_64-3.4/lxml/isoschematron/resources

creating build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/rng

copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/rng

creating build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl

copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl

creating build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.4/lxml/isoschematron/resources/xsl/iso-schematron-xslt1

running build_ext

building 'lxml.etree' extension

creating build/temp.linux-x86_64-3.4

creating build/temp.linux-x86_64-3.4/src

creating build/temp.linux-x86_64-3.4/src/lxml

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/lxml/src/lxml/includes -I/usr/include/python3.4m -I/home/kenju254/workspaces/reverseA/GoogleScraperP/env/include/python3.4m -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-3.4/src/lxml/lxml.etree.o -w

In file included from src/lxml/lxml.etree.c:239:0:

/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory

 #include "libxml/xmlversion.h"

```
                           ^
```

compilation terminated.

/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'bugtrack_url'

  warnings.warn(msg)

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

Cleaning up...
Command /home/kenju254/workspaces/reverseA/GoogleScraperP/env/bin/python3 -c "import setuptools, tokenize;**file**='/home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-aimi250p-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kenju254/workspaces/reverseA/GoogleScraperP/env/include/site/python3.4 failed with error code 1 in /home/kenju254/workspaces/reverseA/GoogleScraperP/env/build/lxml
Storing debug log for failure in /home/kenju254/.pip/pip.log

It fails at some point ..

This is inside a Virtual Environment created with Python3

**Comment by daniel1943** [comment]
I had the same issue and doing above didn't help, turned out issue was lxml running out of memory on 512mb VPS.

If anyone runs on the same issue, easy fix is to create swap file:

dd if=/dev/zero of=swap.img bs=1024k count=1000       # Generates 1GB swapfile.
mkswapswap.img
swapon swap.img

and after you are done:

swapoff swap.img
rm swap.img
