### ISSUE TITLE
google result is null, because google use ajax search

### ISSUE THREAD

**Issue by sbmzhcn** [NikolaiT/GoogleScraper#43]
sometimes google use ajax request to get the serp result, like the url,
https://www.google.com.sg/search?biw=768&bih=799&q=sand+crusher&oq=sand+crusher&gs_l=serp.3..0j0i30l9.35717.106298.6.106480.19.15.0.0.0.0.292.1366.0j7j1.8.0.msedr...0...1c.1.60.serp..11.8.1364.4CtAbfCRlaE&bav=on.2,or.&bvm=bv.82001339,d.cGU&fp=807c0983af5fb146&tch=1&ech=1&psi=fvqgVP2-CdW1oQTkioGoCg.1419836023708.7

google use javascript get the json file, and then parse the json file to html code append to html code.

so the real html source code not contain normal_search_selectors.

i think it in China, use proxy, google redirect the url
https://www.google.com.sg/?gfe_rd=cr&ei=ffqgVObpEpHn-QOa-oC4CQ#q=sand+crusher
so ,default use ajax search.

**Comment by sbmzhcn** [comment]
```python
try:
                    real_source = self.webdriver.execute_script('return document.body.innerHTML;')
                except WebDriverException as e:
                     real_source = self.webdriver.page_source
```
i use the code, and test ok.  like. http://blekko.com/,

**Comment by NikolaiT** [comment]
Thanks! Honestly I didn't understand the full problem, but I appreciate your help a lot!

What would you suggest in http mode?

**Comment by sbmzhcn** [comment]
I'm not a good coder, but as a tester is very good.

**Comment by NikolaiT** [comment]
But your suggestions are great! Made a file AUTHORS and added your name. If you want, I can also add your full name.
