### ISSUE TITLE
NoParserForSearchEngineException

### ISSUE THREAD

**Issue by Euphorbium** [NikolaiT/GoogleScraper#48]
If I try to execute a slightly modified example with multiple search engines added, I get GoogleScraper.parsing.NoParserForSearchEngineException: No such parser for  yandex

    def basic_usage():
    # See in the config.cfg file for possible values
    config = {
        'SCRAPING': {
            'use_own_ip': 'True',
            'keyword': 'Let\'s go bubbles!',
            'search_engines': 'google, yandex',
            'num_pages_for_keyword': 10
        },
        'SELENIUM': {
            'sel_browser': 'phantomjs',
            'num_workers': 10,
        },
        'GLOBAL': {
            'do_caching': 'False'
        }
    }

**Comment by NikolaiT** [comment]
Fixed with:

```python
    search_engines = list({search_engine.strip() for search_engine
        in Config['SCRAPING'].get('search_engines', 'google').split(',') if search_engine.strip()})
```
