### ISSUE TITLE
How to use this tool for detecting plagiarised contents?

### ISSUE THREAD

**Issue by moazam1** [NikolaiT/GoogleScraper#71]
Thanks for making a great library and sharing it with community.

I would like to use this tool to search plagiarised contents on Google, Bing, Duckduckgo, and other search engines. Do you plan to provide this functionality which will take full article and return the match in percentage. More or less like this one: http://bit.ly/17Ujbnd

Thanks

**Comment by NikolaiT** [comment]
Hey, nice you like the tool :)

Detecting plagiarized contents involves getting the actual results (request the web sites that the scraper found) which is not the purpose of this tool. 

You could however very easily write some lines of code that will implement the logic. Look into the examples directory, there you see a file called `usage.py`. This shows how to use GoogleScraper and then add your own logic. 

If you cannot program in Python, then you could hire somebody...

Cheers!

**Comment by moazam1** [comment]
Brilliant @NikolaiT The idea is to take the whole post, split into small chunks, wrap chunks into quotations and then do Google search. If the search result is found, Google will show it in bold letters.

**Comment by NikolaiT** [comment]
You can adapt it that it fits your needs:

https://github.com/NikolaiT/GoogleScraper/blob/master/examples/finding_plagiarized_content.py

**Comment by moazam1** [comment]
Thanks @NikolaiT I will have a look at this. I sent you an email. Cheers!

**Comment by NikolaiT** [comment]
Replied on your mail.

**Comment by moazam1** [comment]
Thank you
