### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by grinono** [NikolaiT/GoogleScraper#80]
When installing with pip i get the following error. 
    

 creating build/temp.linux-x86_64-3.4/src/lxml

    gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-build-4k_k7om1/lxml/src/lxml/includes -I/usr/local/include/python3.4m -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-3.4/src/lxml/lxml.etree.o -w

    In file included from src/lxml/lxml.etree.c:239:0:

    /tmp/pip-build-4k_k7om1/lxml/src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory

    compilation terminated.

    /usr/local/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'bugtrack_url'

      warnings.warn(msg)

    error: command 'gcc' failed with exit status 1

    ----------------------------------------
    Command "/home/bartel/Python-3.4.2/env/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-4k_k7om1/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-336m1iwc-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/bartel/Python-3.4.2/env/include/site/python3.4" failed with error code 1 in /tmp/pip-build-4k_k7om1/lxml

**Comment by NikolaiT** [comment]
You need to install lxml. Probably you don't have python devtools installed.

Try this: http://stackoverflow.com/questions/19955775/error-command-gcc-failed-with-exit-status-1-on-centos
